### ISSUE TITLE
Formula for standard deviation of lognormal distribution

### ISSUE THREAD

**Issue by bryansumalinab** [oswaldogressani/EpiLPS#1]
On lines 84-85 of the _**KerRpostmap.cpp**_ routine under the _**src**_ folder, the formula to compute the standard deviation of $R_t$ is approximated using the standard deviation of the lognormal distribution. The formula that was used is: 

$$\text{Rsd} = \sqrt{\exp\left(\text{sdlogNorm}^2 - 1\right) \times \exp\left(2 \times \text{meanlogNorm} + \text{sdlogNorm}^2\right)}$$

However, the formula seems incorrect because the standard deviation of the lognormal distribution should be: 
                      $$\text{Rsd} = \sqrt{\left(\exp\left(\text{{sdlogNorm}}^2\right) - 1\right) \times \exp\left(2 \times \text{{meanlogNorm}} + \text{{sdlogNorm}}^2\right)}$$
where the exponential of the first term only involves $\text{{sdlogNorm}}^2$, that is, excluding -1.

**Comment by oswaldogressani** [comment]
Formula for standard deviation (Rsd) in KerRpostmap.cpp has been corrected.

**Comment by oswaldogressani** [comment]
Formula for standard deviation (Rsd) in KerRpostmap.cpp has been corrected.
